INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (1, 1,'Grown ups', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (1, 1,'Casablanca', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (1, 2,'Pizza', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (1, 4,'Running with the wolves', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (1, 3,'Jazzy Jeff and the Fresh Prince', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (2, 4,'Frankie Valli and the four seasons', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (2, 2,'The dead south', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (2, 1,'The Bodyguard', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (3, 2,'Jazzy Jeff and the Fresh Prince');
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (3, 4,'Hamilton', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (3, 1,'The Lion King', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (2, 3,'Pistachios', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (2, 3,'Bread', "subtitle");
INSERT INTO todos (user_id, category_id, description, subtitle) VALUES (2, 1,'Monsters Inc', "subtitle");
