INSERT INTO todos (user_id, category_id, description) VALUES (1, 1,'Grown ups');
INSERT INTO todos (user_id, category_id, description) VALUES (1, 1,'Casablanca');
INSERT INTO todos (user_id, category_id, description) VALUES (1, 2,'Pizza');
INSERT INTO todos (user_id, category_id, description) VALUES (1, 4,'Running with the wolves');
INSERT INTO todos (user_id, category_id, description) VALUES (1, 3,'Jazzy Jeff and the Fresh Prince');
INSERT INTO todos (user_id, category_id, description) VALUES (2, 4,'Frankie Valli and the four seasons');
INSERT INTO todos (user_id, category_id, description) VALUES (2, 2,'The dead south');
INSERT INTO todos (user_id, category_id, description) VALUES (2, 1,'The Bodyguard');
INSERT INTO todos (user_id, category_id, description) VALUES (3, 2,'Jazzy Jeff and the Fresh Prince');
INSERT INTO todos (user_id, category_id, description) VALUES (3, 4,'Hamilton');
INSERT INTO todos (user_id, category_id, description) VALUES (3, 1,'The Lion King');